'use strict';

const fs = require('fs');
const path = require('path');

const TYPES = ['Decision', 'Task', 'Insight', 'Project', 'Entity', 'Event', 'Area'];
const FILE_NAMES = {
  Decision: 'Decisions.md',
  Task: 'Tasks.md',
  Insight: 'Insights.md',
  Project: 'Projects.md',
  Entity: 'Entities.md',
  Event: 'Events.md',
  Area: 'Areas.md',
};

function targetProjectionRoot(config, projectRoot) {
  return path.isAbsolute(config.paths.projectionDir)
    ? config.paths.projectionDir
    : path.join(projectRoot, config.paths.projectionDir);
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function compact(text, limit = 240) {
  const oneLine = String(text || '').replace(/\s+/g, ' ').trim();
  if (oneLine.length <= limit) return oneLine;
  return `${oneLine.slice(0, limit - 3)}...`;
}

function escapeYaml(value) {
  return JSON.stringify(value == null ? '' : value);
}

function itemNoteName(item) {
  return `item-${item.id}`;
}

function itemNoteLink(item) {
  return `[[items/${itemNoteName(item)}|${item.title}]]`;
}

function renderRelationFrontmatterList(key, rows, mode) {
  const out = [];
  out.push(`${key}:`);
  if (!rows.length) {
    out.push('  []');
    return out;
  }

  for (const row of rows) {
    if (mode === 'out') {
      out.push(`  - target: ${escapeYaml(`item-${row.target_id}`)}`);
      out.push(`    relation_type: ${escapeYaml(row.relation_type)}`);
      out.push(`    weight: ${Number(row.weight || 1).toFixed(2)}`);
      out.push(`    evidence_ref: ${escapeYaml(row.evidence_ref || '')}`);
    } else {
      out.push(`  - source: ${escapeYaml(`item-${row.source_id}`)}`);
      out.push(`    relation_type: ${escapeYaml(row.relation_type)}`);
      out.push(`    weight: ${Number(row.weight || 1).toFixed(2)}`);
      out.push(`    evidence_ref: ${escapeYaml(row.evidence_ref || '')}`);
    }
  }

  return out;
}

function renderItemNote(item, outgoing, incoming) {
  const lines = [];
  lines.push('---');
  lines.push(`id: ${item.id}`);
  lines.push(`type: ${escapeYaml(item.type)}`);
  lines.push(`state: ${escapeYaml(item.state || 'candidate')}`);
  lines.push(`scope_level: ${escapeYaml(item.scope_level || 'project')}`);
  lines.push(`project_id: ${escapeYaml(item.project_id || '')}`);
  lines.push(`confidence: ${Number(item.confidence || 0).toFixed(2)}`);
  lines.push(`importance: ${Number(item.importance || 0).toFixed(2)}`);
  lines.push(`source_path: ${escapeYaml(item.source_path || '')}`);
  lines.push(`line_start: ${item.line_start || 0}`);
  lines.push(`line_end: ${item.line_end || 0}`);
  lines.push(...renderRelationFrontmatterList('relations_out', outgoing, 'out'));
  lines.push(...renderRelationFrontmatterList('relations_in', incoming, 'in'));
  lines.push('---');
  lines.push('');
  lines.push(`# ${item.title}`);
  lines.push('');
  lines.push(item.body || '');
  lines.push('');
  lines.push('## Evidence');
  lines.push(`- Source: \`${item.source_path || 'unknown'}\``);
  lines.push(`- Lines: ${item.line_start || '?'}-${item.line_end || '?'}`);
  lines.push(`- Snippet: ${compact(item.snippet || item.body || '', 220)}`);
  lines.push('');
  lines.push('## Relations');
  if (!outgoing.length && !incoming.length) {
    lines.push('- _No relations yet._');
  } else {
    for (const rel of outgoing) {
      lines.push(`- ${rel.relation_type} -> [[items/item-${rel.target_id}]]`);
    }
    for (const rel of incoming) {
      lines.push(`- [[items/item-${rel.source_id}]] -> ${rel.relation_type}`);
    }
  }
  lines.push('');

  return lines.join('\n');
}

function renderTypeIndex(type, items) {
  const lines = [];
  lines.push('---');
  lines.push(`generated_at: ${new Date().toISOString()}`);
  lines.push(`type: ${type}`);
  lines.push('format_version: 3');
  lines.push(`item_count: ${items.length}`);
  lines.push('---');
  lines.push('');
  lines.push(`# ${type}s`);
  lines.push('');
  lines.push('> Generated by Hippocore. Each item links to a structured note in `items/` with relation frontmatter.');
  lines.push('');

  if (!items.length) {
    lines.push('_No items yet._');
    lines.push('');
    return lines.join('\n');
  }

  for (const item of items) {
    lines.push(`- ${itemNoteLink(item)}  \`${item.state}\`  score=${Number(item.confidence || 0).toFixed(2)}`);
  }

  lines.push('');
  return lines.join('\n');
}

function renderRelationsIndex(relations, itemsById) {
  const lines = [];
  lines.push('---');
  lines.push(`generated_at: ${new Date().toISOString()}`);
  lines.push('type: Relations');
  lines.push('format_version: 1');
  lines.push(`edge_count: ${relations.length}`);
  lines.push('---');
  lines.push('');
  lines.push('# Relations');
  lines.push('');
  lines.push('> Dual track: wiki links for graph + structured relation fields in each item note frontmatter.');
  lines.push('');

  if (!relations.length) {
    lines.push('_No relations yet._');
    lines.push('');
    return lines.join('\n');
  }

  for (const rel of relations) {
    const from = itemsById.get(rel.from_item_id);
    const to = itemsById.get(rel.to_item_id);
    if (!from || !to) continue;
    lines.push(`- [[items/item-${from.id}|${compact(from.title, 80)}]] -(${rel.relation_type})-> [[items/item-${to.id}|${compact(to.title, 80)}]]`);
  }

  lines.push('');
  return lines.join('\n');
}

function renderProjection(db, config, projectRoot) {
  const root = targetProjectionRoot(config, projectRoot);
  const itemsDir = path.join(root, 'items');

  ensureDir(root);
  ensureDir(itemsDir);

  const rows = db.prepare(`
    SELECT
      m.id,
      m.type,
      m.title,
      m.body,
      m.state,
      m.scope_level,
      m.project_id,
      m.confidence,
      m.importance,
      m.updated_at,
      (
        SELECT e.source_path
        FROM evidence e
        WHERE e.memory_item_id = m.id
        ORDER BY e.id DESC
        LIMIT 1
      ) AS source_path,
      (
        SELECT e.line_start
        FROM evidence e
        WHERE e.memory_item_id = m.id
        ORDER BY e.id DESC
        LIMIT 1
      ) AS line_start,
      (
        SELECT e.line_end
        FROM evidence e
        WHERE e.memory_item_id = m.id
        ORDER BY e.id DESC
        LIMIT 1
      ) AS line_end,
      (
        SELECT e.snippet
        FROM evidence e
        WHERE e.memory_item_id = m.id
        ORDER BY e.id DESC
        LIMIT 1
      ) AS snippet
    FROM memory_items m
    WHERE m.state != 'archived'
    ORDER BY m.updated_at DESC
  `).all();

  const relations = db.prepare(`
    SELECT
      from_item_id,
      to_item_id,
      relation_type,
      weight,
      evidence_ref
    FROM relations
    ORDER BY id DESC
    LIMIT 5000
  `).all();

  const outgoing = new Map();
  const incoming = new Map();

  for (const rel of relations) {
    if (!outgoing.has(rel.from_item_id)) outgoing.set(rel.from_item_id, []);
    if (!incoming.has(rel.to_item_id)) incoming.set(rel.to_item_id, []);

    outgoing.get(rel.from_item_id).push({
      target_id: rel.to_item_id,
      relation_type: rel.relation_type,
      weight: rel.weight,
      evidence_ref: rel.evidence_ref,
    });

    incoming.get(rel.to_item_id).push({
      source_id: rel.from_item_id,
      relation_type: rel.relation_type,
      weight: rel.weight,
      evidence_ref: rel.evidence_ref,
    });
  }

  const itemsById = new Map();
  for (const row of rows) itemsById.set(row.id, row);

  const grouped = new Map();
  for (const type of TYPES) grouped.set(type, []);

  for (const item of rows) {
    const type = TYPES.includes(item.type) ? item.type : 'Event';
    grouped.get(type).push(item);

    const notePath = path.join(itemsDir, `${itemNoteName(item)}.md`);
    fs.writeFileSync(notePath, renderItemNote(item, outgoing.get(item.id) || [], incoming.get(item.id) || []), 'utf8');
  }

  const written = [];
  for (const [type, items] of grouped.entries()) {
    const filePath = path.join(root, FILE_NAMES[type] || `${type}s.md`);
    fs.writeFileSync(filePath, renderTypeIndex(type, items), 'utf8');
    written.push(filePath);
  }

  const relationsPath = path.join(root, 'Relations.md');
  fs.writeFileSync(relationsPath, renderRelationsIndex(relations, itemsById), 'utf8');
  written.push(relationsPath);

  return {
    projectionRoot: root,
    files: written,
    itemNoteCount: rows.length,
    relationCount: relations.length,
  };
}

module.exports = {
  renderProjection,
  targetProjectionRoot,
};
